### ISSUE TITLE
createMany creates only one record

### ISSUE THREAD

**Issue by Olgagr** [aexmachina/factory-girl-sequelize#5]
I'm using version: 0.2.2 and sequelize in version 2.1.3. I've noticed that createMany creates only one record. It also returns created record as a first argument in the callback. I think there are some breaking changes in sequelize that causes that, as with sequelize in version 2.0.6, this method works correctly.

**Comment by aexmachina** [comment]
I don't really use this module, any chance you'd be interested in taking a
look and submitting a PR?

**Comment by Olgagr** [comment]
Thanks for answers. Yes, I can look at it.

**Comment by Olgagr** [comment]
As I can see there is an update to sequelize 3.0.0 version. Not sure if this issue still exists. If so the issue can be reopen.
